spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/thamara_beauty
spring.datasource.username=postgres
spring.datasource.password=04042024
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
